"""Audio domain automation package.

Provides Google AI Studio neural TTS voice synthesis, Win32 Audacity named pipe
IPC and batch polishing, and lossless WAV chapter stitching.
"""

from .audacity_client import (
    apply_preset_file,
    clear_audacity_temp_data,
    delete_checkpoint,
    ensure_audacity_script_pipe_enabled,
    find_preset_file,
    load_checkpoint,
    save_checkpoint,
    send_audacity_command,
    sync_macro_to_audacity,
)
from .chapter_stitcher import (
    get_latest_run_folder,
    scan_sequential_chapters,
    stitch_files,
)
from .tts_generator import (
    CF_UNICODETEXT,
    GMEM_MOVEABLE,
    MANIFEST_FILE_NAME,
    RESPONSE_SELECTOR,
    check_ai_studio_errors,
    check_is_gemini_complete,
    current_mouse_pos,
    ensure_speech_playground_tab,
    extract_total_blocks_count,
    find_input_box,
    find_send_button,
    get_file_md5,
    get_manifest_path,
    human_click,
    human_hover_and_click,
    humanize_text_input,
    is_ai_studio_quota_error,
    is_valid_wav_file,
    kernel32,
    load_or_create_manifest,
    read_voice_options,
    reapply_speech_settings,
    sanitize_script_text,
    save_manifest,
    select_ai_studio_tts_model,
    select_gemini_model,
    send_gemini_prompt,
    set_clipboard_text,
    simulate_human_mouse_move,
    start_clean_gemini_chat,
    user32,
    wait_for_gemini_response,
)

__all__ = [
    "CF_UNICODETEXT",
    "GMEM_MOVEABLE",
    "MANIFEST_FILE_NAME",
    "RESPONSE_SELECTOR",
    "apply_preset_file",
    "check_ai_studio_errors",
    "check_is_gemini_complete",
    "clear_audacity_temp_data",
    "current_mouse_pos",
    "delete_checkpoint",
    "ensure_audacity_script_pipe_enabled",
    "ensure_speech_playground_tab",
    "extract_total_blocks_count",
    "find_input_box",
    "find_preset_file",
    "find_send_button",
    "get_file_md5",
    "get_latest_run_folder",
    "get_manifest_path",
    "human_click",
    "human_hover_and_click",
    "humanize_text_input",
    "is_ai_studio_quota_error",
    "is_valid_wav_file",
    "kernel32",
    "load_checkpoint",
    "load_or_create_manifest",
    "read_voice_options",
    "reapply_speech_settings",
    "sanitize_script_text",
    "save_checkpoint",
    "save_manifest",
    "scan_sequential_chapters",
    "select_ai_studio_tts_model",
    "select_gemini_model",
    "send_audacity_command",
    "send_gemini_prompt",
    "set_clipboard_text",
    "simulate_human_mouse_move",
    "start_clean_gemini_chat",
    "stitch_files",
    "sync_macro_to_audacity",
    "user32",
    "wait_for_gemini_response",
]
